#!/usr/bin/env bash
# Script to shows info on subdomains.

domain_information() {
    ANSWER=$(dig $2 | grep -A1 'ANSWER SECTION:' | awk 'NR==2 {print $0}')
    echo "The subdomain $1 is a $(echo $ANSWER | awk '{print $4}') record and points to $(echo $ANSWER | awk '{print $5}')"
}

if [ "$#" == 1 ]; then
    subdomains=('www' 'lb-01' 'web-01' 'web-02')
    for d in "${subdomains[@]}"; do
	CONCAT="$d.$1"
	domain_information $d $CONCAT
    done
else
    CONCAT="$2.$1"
    domain_information $2 $CONCAT
fi
