#!/usr/bin/env bash
# Script to transfe a file from our client to a server
# scp must transfer file to user's home directory
# Host key must be disabled when using scp

if [ $# -lt 3 ]
then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
   scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi
