#!/usr/bin/env bash
# Script that configures a new Ubuntu machine

sudo apt-get -y update
sudo apt-get -y install nginx

sudo service nginx start

sudo ufw allow 'Nginx HTTP'

sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

str_change="server_name _;\n\trewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" 
sudo sed -i "s/server_name_;/$str_change/" /etc/nginx/sites-enabled/default

sudo service nginx restart
