#!/usr/bin/env bash
#Configure your Nginx server to have an error 404 and a string

sudo apt-get -y update
sudo apt-get -y install nginx

sudo service nginx start

# Allow ngix on firewall
sudo ufw allow 'Nginx HTTP'

# Gives ownership to website for editing
sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
str_change="server_name _;\n\trewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" 
sudo sed -i "s/server_name_;/$str_change/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
str_change="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$str_change/" /etc/nginx/sites-enabled/default

sudo service nginx restart
