#!/usr/bin/env bash
# web-01 and web-02 configuring HTTP header response

# Update and install package nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

#Redirection process
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/colly-m permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Creates a 404 custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Creates a HTTP header response
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Syntax errors configuration tests
sudo nginx -t

# Restarts nginx after configurations
sudo service nginx restart
