#!/usr/bin/env bash
# Bash script to manage process manage_my_process by starting stopping or restarting

PID_FILE="/var/run/my_process.pid"

if [ "$1" == "start" ]
then
	./manage_my_process &
	echo $$ > $PID_FILE
	echo "manage_my_process started"
		
elif [ "$1" == "stop" ]
then
	pid=$(pgrep -f ./manage_my_process)
	kill $pid
	rm $PID_FILE
	echo "manage_my_process stopped"

elif [ "$1" == "restart" ]
then
	pid=$(pgrep -f ./manage_my_process)
	kill $pid
	rm $PID_FILE
	./manage_my_process &
	echo $$ > $PID_FILE
	echo "manage_my_process restarted"

else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
