#!/usr/bin/env bash
# Script to displays text with sleep 2 in between
# I am invincible!!! When receiving a SIGTERM signal


trap 'echo "I am invincible!!!"' 15
while true;
do
	echo "To infinity and beyond"
	sleep 2
done
