#!/usr/bin/env bash
# This script is displaying contents of file /etc/passwd

f_name="/etc/passwd"

while IFS=':' read -r username _ uid gid password info home shell; do
	echo "The user $username is part of the $gid gang,"\
	"lives in $home, and rides $shell."\
	"$uid's place is protected by the passcode $password,"\
	"more info about the user here: $info"
done < "$f_name"
