#!/usr/bin/env bash
# This script displays hours from 0 t0 12 and minutes from 1 to 59

hrs=0

while [ $hrs -le 12 ]
do
	echo "Hour: $hrs"
	min=1
	while [ $min -le 59 ]
	do
		echo "$min"
		(( min++ ))
	done
	(( hrs++ ))
done
