#!/usr/bin/env bash
# Bash script to configure ubuntu server

sudo cp /etc/hosts ~/hosts.new
sudo sed -i s/127.0.0.2/127.0.0.1/ ~/hosts.new
echo "facebook.com 8.8.8.8" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
